#!/usr/bin/env python
""""U-QASAR Command Line Interpreter."""

import click
import requests


@click.group()
def cli():
    """U-Qasar CLI 0.1 version.

    This is a proof of concept about how can be implented a CLI tool.
    """
    click.echo('U-Qasar CLI is working')

# Read & check the config
#  Prepare URL


@cli.command('projects')
def projects():
    """Retrieve all existing Projects in platform."""
    click.echo('%s all you projects belong to us!!' % (project_name))


@cli.command('project')
def projects(project_name):
    """Retrieve an existing Project in platform by name."""
    click.echo('all you projects belong to us!!')


@cli.command('qmodels')
def qmodels():
    """Retrieve all existing QModels in platform."""
    click.echo('all you qmodels belong to us!!')


@cli.command('historic')
def qmodels():
    """Retrieve all existing Historic Values in platform."""
    click.echo('all you Historic Values belong to us!!')

if __name__ == "__main__":
    cli()
